spring:
    application:
        name: ${SPRING_APPLICATION_NAME}
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10

    h2:
        console:
            enabled: true

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true

    flyway:
        baseline-on-migrate: true
        validate-on-migrate: true

    logging:
        level:
            root: info
            org.springframework.aop: DEBUG

pokeapi:
    base-url: ${POKE_API_BASE_URL}