spring:
    application:
        name: pokeapi-soap-service
    datasource:
        url: jdbc:mysql://34.135.186.85:3306/pokeapi
        username: root
        password: bankaya
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10

    h2:
        console:
            enabled: true

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true

    flyway:
        enabled: true
        locations: classpath:db/migration

    logging:
        level:
            root: info
